# -*- coding: utf-8 -*-
"""Баранов Д.А. ИВТ 2.1. ЛР №5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXS9RH4j5WDtz4tyvAFTJcz-HDfCkfAs

# Лабораторная работа №5
Баранов Д.А. ИВТ 2.1

Задание 1: Прогнозирование временных рядов
(SimpleRNN, LSTM и Bidirectional LSTM)

1. Загрузка и предобработка данных
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, LSTM, Bidirectional
import math

# Загрузка данных
dataset = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv',
                       usecols = [1], engine = 'python', skipfooter = 3)
data = dataset.values.astype('float32')

# Нормализация данных
scaler = MinMaxScaler(feature_range = (0, 1))
data = scaler.fit_transform(data)

# Разделение на обучающую и тестовую выборки
train_size = int(len(data) * 0.67)
test_size = len(data) - train_size
train, test = data[0:train_size,:], data[train_size:len(data),:]
print(f"Размер обучающей выборки: {len(train)}, размер тестовой выборки: {len(test)}")

# Функция для создания датасета с временными шагами
def create_dataset(dataset, look_back = 1):
  X, Y = [], []
  for i in range(len(dataset) - look_back):
    X.append(dataset[i:(i + look_back), 0])
    Y.append(dataset[i + look_back, 0])
  return np.array(X), np.array(Y)

# Создание датасетов с временными шагами
look_back = 3
X_train, y_train = create_dataset(train, look_back)
X_test, y_test = create_dataset(test, look_back)

# Преобразование входных данных для RNN [samples, time steps, features]
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

"""2. Создание и обучение модели SimpleRNN"""

# Создание модели SimpleRNN
def create_simple_rnn_model():
  model = Sequential()
  model.add(SimpleRNN(units = 50, activation = 'relu', input_shape = (look_back, 1)))
  model.add(Dense(1))
  model.compile(optimizer = 'adam', loss = 'mean_squared_error')
  return model

# Обучение модели SimpleRNN
simple_rnn_model = create_simple_rnn_model()
simple_rnn_history = simple_rnn_model.fit(X_train, y_train, epochs = 100, batch_size = 32,
                                          validation_data = (X_test, y_test), verbose = 2)

# Прогнозирование
simple_rnn_train_predict = simple_rnn_model.predict(X_train)
simple_rnn_test_predict = simple_rnn_model.predict(X_test)

# Обратное преобразование прогнозов
simple_rnn_train_predict = scaler.inverse_transform(simple_rnn_train_predict)
simple_rnn_test_predict = scaler.inverse_transform(simple_rnn_test_predict)
y_train_inv = scaler.inverse_transform([y_train])
y_test_inv = scaler.inverse_transform([y_test])

# Расчет RMSE
simple_rnn_train_rmse = math.sqrt(mean_squared_error(y_train_inv[0],
  simple_rnn_train_predict[:, 0]))
simple_rnn_test_rmse = math.sqrt(mean_squared_error(y_test_inv[0],
  simple_rnn_test_predict[:, 0]))
print(f'SimpleRNN - Ошибка на обучающей выборке (RMSE): {simple_rnn_train_rmse}')
print(f'SimpleRNN - Ошибка на тестовой выборке (RMSE): {simple_rnn_test_rmse}')

"""3. Создание и обучение модели LSTM"""

# Создание модели LSTM
def create_lstm_model():
  model = Sequential()
  model.add(LSTM(units = 50, activation = 'relu', input_shape = (look_back, 1)))
  model.add(Dense(1))
  model.compile(optimizer = 'adam', loss = 'mean_squared_error')
  return model

# Обучение модели LSTM
lstm_model = create_lstm_model()
lstm_history = lstm_model.fit(X_train, y_train, epochs = 100, batch_size = 32,
                              validation_data = (X_test, y_test), verbose = 2)

# Прогнозирование
lstm_train_predict = lstm_model.predict(X_train)
lstm_test_predict = lstm_model.predict(X_test)

# Обратное преобразование прогнозов
lstm_train_predict = scaler.inverse_transform(lstm_train_predict)
lstm_test_predict = scaler.inverse_transform(lstm_test_predict)

# Расчет RMSE
lstm_train_rmse = math.sqrt(mean_squared_error(y_train_inv[0], lstm_train_predict[:,0]))
lstm_test_rmse = math.sqrt(mean_squared_error(y_test_inv[0], lstm_test_predict[:,0]))
print(f'LSTM - Ошибка на обучающей выборке (RMSE): {lstm_train_rmse}')
print(f'LSTM - Ошибка на тестовой выборке (RMSE): {lstm_test_rmse}')

"""4. Создание и обучение модели Bidirectional LSTM"""

# Создание модели Bidirectional LSTM
def create_bidirectional_lstm_model():
  model = Sequential()
  model.add(Bidirectional(LSTM(units = 50, activation = 'relu'), input_shape = (look_back, 1)))
  model.add(Dense(1))
  model.compile(optimizer = 'adam', loss = 'mean_squared_error')
  return model

# Обучение модели Bidirectional LSTM
bidirectional_lstm_model = create_bidirectional_lstm_model()
bidirectional_lstm_history = bidirectional_lstm_model.fit(X_train, y_train, epochs = 100,
                                                          batch_size = 32, validation_data = (X_test, y_test),
                                                          verbose = 2)

# Прогнозирование
bidirectional_lstm_train_predict = bidirectional_lstm_model.predict(X_train)
bidirectional_lstm_test_predict = bidirectional_lstm_model.predict(X_test)

# Обратное преобразование прогнозов
bidirectional_lstm_train_predict = scaler.inverse_transform(bidirectional_lstm_train_predict)
bidirectional_lstm_test_predict = scaler.inverse_transform(bidirectional_lstm_test_predict)

# Расчет RMSE
bidirectional_lstm_train_rmse = math.sqrt(mean_squared_error(y_train_inv[0],
                                                             bidirectional_lstm_train_predict[:,0]))
bidirectional_lstm_test_rmse = math.sqrt(mean_squared_error(y_test_inv[0],
                                                            bidirectional_lstm_test_predict[:,0]))

print(f'Bidirectional LSTM - Ошибка на обучающей выборке (RMSE): {bidirectional_lstm_train_rmse}')
print(f'Bidirectional LSTM - Ошибка на тестовой выборке (RMSE): {bidirectional_lstm_test_rmse}')

"""5. Визуализация результатов"""

# Подготовка данных для визуализации
train_plot = np.empty_like(data)
train_plot[:, :] = np.nan
train_plot[look_back:len(simple_rnn_train_predict) + look_back, :] = simple_rnn_train_predict

test_plot = np.empty_like(data)
test_plot[:, :] = np.nan
test_plot[len(simple_rnn_train_predict) + (look_back * 2):len(data), :] = simple_rnn_test_predict

# Визуализация результатов SimpleRNN
plt.figure(figsize = (15, 6))
plt.plot(scaler.inverse_transform(data), label = 'Исходные данные')
plt.plot(train_plot, label = 'Прогноз на обучающей выборке (SimpleRNN)')
plt.plot(test_plot, label = 'Прогноз на тестовой выборке (SimpleRNN)')
plt.title('Прогнозирование временного ряда с использованием SimpleRNN')
plt.xlabel('Месяц')
plt.ylabel('Количество пассажиров')
plt.legend()
plt.show()

# Сравнение ошибок модели
models = ['SimpleRNN', 'LSTM', 'Bidirectional LSTM']
train_rmse = [simple_rnn_train_rmse, lstm_train_rmse, bidirectional_lstm_train_rmse]
test_rmse = [simple_rnn_test_rmse, lstm_test_rmse, bidirectional_lstm_test_rmse]

plt.figure(figsize = (10, 6))
x = np.arange(len(models))
width = 0.35

plt.bar(x - width/2, train_rmse, width, label = 'Обучающая выборка')
plt.bar(x + width/2, test_rmse, width, label = 'Тестовая выборка')

plt.xlabel('Модель')
plt.ylabel('RMSE')
plt.title('Сравнение ошибок моделей')
plt.xticks(x, models)
plt.legend()
plt.show()